name: Qodana
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'feat-*'
      - 'releases-*'

jobs:
  qodana:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: --baseline qodana.sarif.json
          pr-mode: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_489541164 }}

      - name: 'Display Qodana logs'
        if: failure()
        run: |
          echo "Qodana logs:"
          cat /home/runner/work/_temp/qodana/results/qodana.sarif.json || true